version: '3.7'

services:

  db:
    image: mysql:5.7
    container_name: oc3-db-dev
    restart: unless-stopped
    volumes:
      - oc3-module:/var/lib/mysql
      - ./.docker/mysql/init.sql:/usr/bin/init.sql
      - ./.docker/mysql/entrypoint.sh:/usr/bin/entrypoint.sh
    command: /bin/bash -c "/usr/bin/entrypoint.sh"
    networks:
      - app-network

  backend:
    image: registry.git.innokassa.ru/byurrer/docker-images/php7.1-fpm:dev
    container_name: oc3-backend-dev
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:172.16.2.1"
    depends_on: 
      - db
    volumes:
      - ./logs/:/var/www/html/logs/
      - ./opencart/:/var/www/html/
      - ./src/admin/controller/extension/module/innokassa.php:/var/www/html/admin/controller/extension/module/innokassa.php
      - ./src/catalog/controller/extension/module/innokassa.php:/var/www/html/catalog/controller/extension/module/innokassa.php
      - ./src/admin/language/ru-ru/extension/module/innokassa.php:/var/www/html/admin/language/ru-ru/extension/module/innokassa.php
      - ./src/admin/model/extension/module/innokassa.php:/var/www/html/admin/model/extension/module/innokassa.php
      - ./src/admin/view/template/extension/module/innokassa.twig:/var/www/html/admin/view/template/extension/module/innokassa.twig
      - ./src/admin/view/template/extension/module/innokassa-btn-new-receipt.js:/var/www/html/admin/view/template/extension/module/innokassa-btn-new-receipt.js
      - ./src/admin/view/template/extension/module/innokassa-rb4cms.js:/var/www/html/admin/view/template/extension/module/innokassa-rb4cms.js
      - ./src/system/library/innokassa/:/var/www/html/system/library/innokassa/
    networks:
      - app-network

  webserver:
    image: registry.git.innokassa.ru/byurrer/docker-images/apache2:latest
    container_name: oc3-webserver-dev
    restart: unless-stopped
    depends_on: 
      - backend
    volumes:
      - ./.docker/webserver/host.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/:/var/www/html/logs/
      - ./opencart/:/var/www/html/
      - ./src/admin/controller/extension/module/innokassa.php:/var/www/html/admin/controller/extension/module/innokassa.php
      - ./src/catalog/controller/extension/module/innokassa.php:/var/www/html/catalog/controller/extension/module/innokassa.php
      - ./src/admin/language/ru-ru/extension/module/innokassa.php:/var/www/html/admin/language/ru-ru/extension/module/innokassa.php
      - ./src/admin/model/extension/module/innokassa.php:/var/www/html/admin/model/extension/module/innokassa.php
      - ./src/admin/view/template/extension/module/innokassa.twig:/var/www/html/admin/view/template/extension/module/innokassa.twig
      - ./src/admin/view/template/extension/module/innokassa-btn-new-receipt.js:/var/www/html/admin/view/template/extension/module/innokassa-btn-new-receipt.js
      - ./src/admin/view/template/extension/module/innokassa-rb4cms.js:/var/www/html/admin/view/template/extension/module/innokassa-rb4cms.js
      - ./src/system/library/innokassa/:/var/www/html/system/library/innokassa/
    networks:
      app-network:
        ipv4_address: 172.16.2.4

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.1/24

volumes:
  oc3-module:
